SELECT *
FROM SYSADM.PS_CLASS_TBL
ORDER BY STRM, CLASS_NBR;
--Fields: STRM (0810), DESCR (Intro to BIO), CLASS_NBR (49,558 int should be string), SUBJECT (BIO, CHEM)
--Note that some class records have discrepancies between the DESCR and the SUBJECT, 
--say Workshop: ENGL and MATH, or Special Topics in MATH and BIO

SELECT count (*)
FROM SYSADM.PS_CLASS_TBL;
--3900 rows

SELECT * 
FROM SYSADM.PS_STDNT_ENRL
ORDER BY EMPLID, STRM;
--EMPLID, ACAD_CAREER, INSTITUTION, STRM, CLASS_NBR, CRSE_CAREER (identical to ACAD_CAREER), 
--SESSION_CODE, STDNT_ENRL_STATUS, CRSE_GRADE_OFF

SELECT count (*)
FROM SYSADM.PS_STDNT_ENRL;
--initially 0 values due to end of line error
--10001 after selecting the whole block and then run (1 duplicate, probably duplicate insertion from repeated attempts)


SELECT *
FROM SYSADM.PS_TERM_TBL
ORDER BY STRM;
--Fields: INSTITUTION (CSUOH), ACAD_CAREER (GRAD, LAW, UGRD), STRM(0820), DESCR (Spring Semester 2015)

SELECT count(*)
FROM SYSADM.PS_TERM_TBL;
--114 rows



SELECT ACAD_CAREER, CRSE_CAREER
FROM SYSADM.PS_STDNT_ENRL
WHERE ACAD_CAREER <> CRSE_CAREER;

SELECT DISTINCT SESSION_CODE
FROM SYSADM.PS_STDNT_ENRL;
--only one value: 1

SELECT DISTINCT STDNT_ENRL_STATUS
FROM SYSADM.PS_STDNT_ENRL;
--values EN, WL, DR

SELECT DISTINCT CRSE_GRADE_OFF
FROM SYSADM.PS_STDNT_ENRL;
--A, B, C, P, N, NULL

SELECT DISTINCT INSTITUTION
FROM SYSADM.PS_STDNT_ENRL;
--just CSUOH

SELECT MIN(EMPLID), MAX(EMPLID)
FROM SYSADM.PS_STDNT_ENRL;
--10000000000 to 10000009999

SELECT EMPLID, MIN(STRM), MAX(STRM)
FROM SYSADM.PS_STDNT_ENRL
GROUP BY EMPLID 
HAVING MIN(STRM)<>MAX(STRM);
--no EMPLID that have multiple terms

SELECT EMPLID, COUNT(DISTINCT STRM)
FROM SYSADM.PS_STDNT_ENRL
GROUP BY EMPLID
HAVING COUNT(DISTINCT STRM)>1
ORDER BY EMPLID;

SELECT EMPLID, COUNT(DISTINCT CLASS_NBR)
FROM SYSADM.PS_STDNT_ENRL
GROUP BY EMPLID
HAVING COUNT(DISTINCT CLASS_NBR)>1
ORDER BY EMPLID;

SELECT EMPLID, STRM
FROM SYSADM.PS_STDNT_ENRL
WHERE EMPLID=10000000032;
--this is a duplicate record that I introduced

SELECT STRM, COUNT (DISTINCT EMPLID)
FROM SYSADM.PS_STDNT_ENRL
GROUP BY STRM
--HAVING COUNT(DISTINCT EMPLID)>1
ORDER BY STRM;
--each STRM has multiple EMPLID


SELECT 
	DISTINCT EMPLID
	, ACAD_CAREER
	, STRM
	, CLASS_NBR
	, TO_CHAR (CLASS_NBR) AS CLASS_NBR_STR
	, STDNT_ENRL_STATUS
	, CRSE_GRADE_OFF 
FROM SYSADM.PS_STDNT_ENRL
ORDER BY EMPLID, STRM;
--EMPLID, ACAD_CAREER, INSTITUTION, STRM, CLASS_NBR, CRSE_CAREER (identical to ACAD_CAREER), 
--SESSION_CODE, STDNT_ENRL_STATUS, CRSE_GRADE_OFF

--distinct terms with description filter from fall 2020 and later
--39 distinct terms
SELECT DISTINCT STRM, DESCR
FROM SYSADM.PS_TERM_TBL
--WHERE STRM >= 990
ORDER BY STRM;

SELECT 
	STRM 
	, CLASS_NBR
	, TO_CHAR (CLASS_NBR) AS CLASS_NBR_STR
	, DESCR
	, SUBJECT
	--this flags out records that have discrepancies between the DESCR and the SUBJECT, 
	--say Workshop: ENGL and MATH, or Special Topics in MATH and BIO
	, CASE WHEN SUBSTR(DESCR, -4) LIKE '%' || SUBJECT THEN 0
		ELSE 1
		END AS DESCR_SUBJECT_MISMATCH
	, CASE WHEN (SUBSTR(DESCR, -3) = SUBJECT OR SUBSTR(DESCR, -4) = SUBJECT OR SUBSTR(DESCR, -2) = SUBJECT) THEN 0
		ELSE 1
		END AS DESCR_SUBJECT_MISMATCH2
FROM SYSADM.PS_CLASS_TBL
ORDER BY STRM, CLASS_NBR;
--Fields: STRM (0810), DESCR (Intro to BIO), CLASS_NBR (49,558 int should be string), SUBJECT (BIO, CHEM)

SELECT EMPLID, MIN(STRM) AS FIRST_TERM, MAX(STRM) AS LAST_TERM
FROM SYSADM.PS_STDNT_ENRL
WHERE 

--Fall Cohort for each EMPLID
SELECT 
	DISTINCT ef.EMPLID
	, MIN(ef.TERM_DESCR) AS FALL_COHORT_DESCR
FROM
--enrollment in Fall terms
(--start ef
SELECT
		DISTINCT se.EMPLID
		, se.STRM AS TERM
		, term.DESCR AS TERM_DESCR
FROM 
	(--start se
	SELECT 
		DISTINCT EMPLID
		, STRM
		, STDNT_ENRL_STATUS
	FROM SYSADM.PS_STDNT_ENRL
	WHERE STDNT_ENRL_STATUS = 'EN'

	)se --end se
	
	INNER JOIN

	(--start term
	SELECT DISTINCT STRM, DESCR
	FROM SYSADM.PS_TERM_TBL
	WHERE DESCR LIKE 'Fall%'
	ORDER BY STRM
	)term --end term
	ON se.STRM=term.STRM
--ORDER BY  se.STRM, se.EMPLID
)ef --end ef
GROUP BY ef.EMPLID
ORDER BY ef.EMPLID



--Join the data
SELECT
		DISTINCT se.EMPLID
		, se.ACAD_CAREER
		, se.STRM AS TERM
		, term.DESCR AS TERM_DESCR
		, coh.FALL_COHORT_DESCR
		, se.CLASS_NBR
		, se.CLASS_NBR_STR
		, se.STDNT_ENRL_STATUS
		, se.CRSE_GRADE_OFF 
		, CASE WHEN se.STDNT_ENRL_STATUS = 'EN' THEN NVL(se.CRSE_GRADE_OFF, 'N')
			ELSE 'N'
			END AS CRSE_GRADE_MODIFIED
		, CASE WHEN se.STDNT_ENRL_STATUS = 'EN' AND se.CRSE_GRADE_OFF IN ('D', 'F') THEN 1
			WHEN se.STDNT_ENRL_STATUS = 'WL' THEN 1
			ELSE 0
			END AS DFW_FLAG

		, CASE WHEN term.DESCR LIKE 'Fall%' THEN 'FALL'
			WHEN term.DESCR LIKE 'Spring%' THEN 'SPRING'
			WHEN term.DESCR LIKE 'Summer%' THEN 'SUMMER' 
			ELSE 'OTHER'
			END AS TERM_TYPE
		, class.DESCR AS CLASS_DESCR
		, class.SUBJECT
		, class.DESCR_SUBJECT_MISMATCH
		
	
FROM 
	(--start se
	SELECT 
		DISTINCT EMPLID
		, ACAD_CAREER
		, STRM
		, CLASS_NBR
		, TO_CHAR (CLASS_NBR) AS CLASS_NBR_STR
		, STDNT_ENRL_STATUS
		, CRSE_GRADE_OFF 
	FROM SYSADM.PS_STDNT_ENRL
	ORDER BY EMPLID, STRM
	)se --end se
	
	LEFT JOIN

	(--start term
	SELECT DISTINCT STRM, DESCR
	FROM SYSADM.PS_TERM_TBL
	ORDER BY STRM
	)term --end term
	ON se.STRM=term.STRM
	
	LEFT JOIN
	
	(--start class
	SELECT 
		STRM 
		, CLASS_NBR
		, TO_CHAR (CLASS_NBR) AS CLASS_NBR_STR
		, DESCR
		, SUBJECT
		--this flags out records that have discrepancies between the DESCR and the SUBJECT, say Workshop: ENGL and MATH, or Special Topics in MATH and BIO
		, CASE WHEN SUBSTR(DESCR, -4) LIKE '%' || SUBJECT THEN 0
			ELSE 1
			END AS DESCR_SUBJECT_MISMATCH
		, CASE WHEN (SUBSTR(DESCR, -3) = SUBJECT OR SUBSTR(DESCR, -4) = SUBJECT OR SUBSTR(DESCR, -2) = SUBJECT) THEN 0
			ELSE 1
			END AS DESCR_SUBJECT_MISMATCH2
	FROM SYSADM.PS_CLASS_TBL
	ORDER BY STRM, CLASS_NBR
	--Fields: STRM (0810), DESCR (Intro to BIO), CLASS_NBR (49,558 int should be string), SUBJECT (BIO, CHEM)
	)class --end class
	ON se.STRM=class.STRM AND se.CLASS_NBR=class.CLASS_NBR
	
	LEFT JOIN
	
	(--start coh
	--Fall Cohort for each EMPLID
	SELECT 
		DISTINCT ef.EMPLID
		, MIN(ef.TERM_DESCR) AS FALL_COHORT_DESCR
	FROM
		--enrollment in Fall terms
		(--start ef
		SELECT
			DISTINCT se.EMPLID
			, se.STRM AS TERM
			, term.DESCR AS TERM_DESCR
		FROM 
			(--start se
			SELECT 
			DISTINCT EMPLID
			, STRM
			, STDNT_ENRL_STATUS
			FROM SYSADM.PS_STDNT_ENRL
			WHERE STDNT_ENRL_STATUS = 'EN'

			)se --end se
	
		INNER JOIN

		(--start term
		SELECT DISTINCT STRM, DESCR
		FROM SYSADM.PS_TERM_TBL
		WHERE DESCR LIKE 'Fall%'
		ORDER BY STRM
		)term --end term
		ON se.STRM=term.STRM
		)ef --end ef
	GROUP BY ef.EMPLID
	ORDER BY ef.EMPLID
	)coh --end coh
	ON se.EMPLID = coh.EMPLID
	
ORDER BY se.EMPLID, se.STRM;
	


--Retention Fall 2024 (1110) to Fall 2025 (1140)
SELECT

	SUM (CASE WHEN ret.EMPLID IS NULL THEN 0
		ELSE 1
		END)/COUNT (coh.EMPLID) AS RETENTION_RATE
FROM

	--Fall 2024 cohort:
	(-- start coh
	SELECT 
		DISTINCT EMPLID
	FROM SYSADM.PS_STDNT_ENRL
	WHERE STDNT_ENRL_STATUS = 'EN'
		AND STRM = :STRM --'1110'
	)coh --end coh
	
	LEFT JOIN	
	
	--retained in Fall 2025 cohort
	(--start ret
	SELECT 
		DISTINCT EMPLID
	FROM SYSADM.PS_STDNT_ENRL
	WHERE STDNT_ENRL_STATUS = 'EN'
		AND STRM = :STRM
		AND EMPLID IN	
			(
			SELECT 
				DISTINCT EMPLID
			FROM SYSADM.PS_STDNT_ENRL
			WHERE STDNT_ENRL_STATUS = 'EN'
				AND STRM = TO_CHAR(TO_NUMBER(:STRM)+30)--'1140'
			)
	)ret --end ret
ON coh.EMPLID = ret.EMPLID
	


--enrollment by Fall term 
SELECT
		se.STRM AS TERM
		, term.DESCR AS TERM_DESCR
		, count (STDNT_ENRL_STATUS)		
	
FROM 
	(--start se
	SELECT 
		DISTINCT EMPLID
		, ACAD_CAREER
		, STRM
		, CLASS_NBR
		, TO_CHAR (CLASS_NBR) AS CLASS_NBR_STR
		, STDNT_ENRL_STATUS
		, CRSE_GRADE_OFF 
	FROM SYSADM.PS_STDNT_ENRL
	ORDER BY EMPLID, STRM
	)se --end se
	
	LEFT JOIN

	(--start term
	SELECT DISTINCT STRM, DESCR
	FROM SYSADM.PS_TERM_TBL
	ORDER BY STRM
	)term --end term
	ON se.STRM=term.STRM
	
	LEFT JOIN
	
	(--start class
	SELECT 
		STRM 
		, CLASS_NBR
		, TO_CHAR (CLASS_NBR) AS CLASS_NBR_STR
		, DESCR
		, SUBJECT
		--this flags out records that have discrepancies between the DESCR and the SUBJECT, say Workshop: ENGL and MATH, or Special Topics in MATH and BIO
		, CASE WHEN SUBSTR(DESCR, -4) LIKE '%' || SUBJECT THEN 0
			ELSE 1
			END AS DESCR_SUBJECT_MISMATCH
		, CASE WHEN (SUBSTR(DESCR, -3) = SUBJECT OR SUBSTR(DESCR, -4) = SUBJECT OR SUBSTR(DESCR, -2) = SUBJECT) THEN 0
			ELSE 1
			END AS DESCR_SUBJECT_MISMATCH2
	FROM SYSADM.PS_CLASS_TBL
	ORDER BY STRM, CLASS_NBR
	--Fields: STRM (0810), DESCR (Intro to BIO), CLASS_NBR (49,558 int should be string), SUBJECT (BIO, CHEM)
	)class --end class
	ON se.STRM=class.STRM AND se.CLASS_NBR=class.CLASS_NBR
WHERE se.STDNT_ENRL_STATUS = 'EN'
GROUP BY se.STRM, term.DESCR
ORDER BY se.STRM;

--enrollment by term and ACAD_CAREER
SELECT
		se.ACAD_CAREER
		, se.STRM AS TERM
		, term.DESCR AS TERM_DESCR
		, count (STDNT_ENRL_STATUS)		
	
FROM 
	(--start se
	SELECT 
		DISTINCT EMPLID
		, ACAD_CAREER
		, STRM
		, CLASS_NBR
		, TO_CHAR (CLASS_NBR) AS CLASS_NBR_STR
		, STDNT_ENRL_STATUS
		, CRSE_GRADE_OFF 
	FROM SYSADM.PS_STDNT_ENRL
	ORDER BY EMPLID, STRM
	)se --end se
	
	LEFT JOIN

	(--start term
	SELECT DISTINCT STRM, DESCR
	FROM SYSADM.PS_TERM_TBL
	ORDER BY STRM
	)term --end term
	ON se.STRM=term.STRM
	
	LEFT JOIN
	
	(--start class
	SELECT 
		STRM 
		, CLASS_NBR
		, TO_CHAR (CLASS_NBR) AS CLASS_NBR_STR
		, DESCR
		, SUBJECT
		--this flags out records that have discrepancies between the DESCR and the SUBJECT, say Workshop: ENGL and MATH, or Special Topics in MATH and BIO
		, CASE WHEN SUBSTR(DESCR, -4) LIKE '%' || SUBJECT THEN 0
			ELSE 1
			END AS DESCR_SUBJECT_MISMATCH
		, CASE WHEN (SUBSTR(DESCR, -3) = SUBJECT OR SUBSTR(DESCR, -4) = SUBJECT OR SUBSTR(DESCR, -2) = SUBJECT) THEN 0
			ELSE 1
			END AS DESCR_SUBJECT_MISMATCH2
	FROM SYSADM.PS_CLASS_TBL
	ORDER BY STRM, CLASS_NBR
	--Fields: STRM (0810), DESCR (Intro to BIO), CLASS_NBR (49,558 int should be string), SUBJECT (BIO, CHEM)
	)class --end class
	ON se.STRM=class.STRM AND se.CLASS_NBR=class.CLASS_NBR
WHERE se.STDNT_ENRL_STATUS = 'EN'
GROUP BY se.ACAD_CAREER, se.STRM, term.DESCR
ORDER BY se.ACAD_CAREER, se.STRM;




