
-- 1. Create the user
CREATE USER SYSADM IDENTIFIED BY StrongPassword123;

-- 2. Grant basic privileges to the new user
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO SYSADM;

-- 2.1 Add Quota for data storage
ALTER USER SYSADM QUOTA UNLIMITED ON SYSTEM;
--
-- 3. Create the tables, one at a time:
--
/*
    Class Table
*/
CREATE TABLE SYSADM.PS_CLASS_TBL (
    STRM VARCHAR2(4),
    DESCR VARCHAR2(30),
    CLASS_NBR NUMBER(38,0),
    SUBJECT VARCHAR2(8)
)

/*
    Create Term
*/
CREATE TABLE SYSADM.PS_TERM_TBL (
	INSTITUTION VARCHAR2(5),
	ACAD_CAREER VARCHAR2(4),
	STRM VARCHAR2(4),
	DESCR VARCHAR2(30)
)

/*
    Create table
*/
CREATE TABLE SYSADM.PS_STDNT_ENRL (
    EMPLID VARCHAR2(11),
    ACAD_CAREER VARCHAR2(4),
    INSTITUTION VARCHAR2(5),
    STRM VARCHAR2(4),
    CLASS_NBR NUMBER(38,0),
    CRSE_CAREER VARCHAR2(4),
    SESSION_CODE VARCHAR2(3),
    STDNT_ENRL_STATUS VARCHAR2(2),
    CRSE_GRADE_OFF VARCHAR2(3)
)